export const mailData = [
  {
    id: 1,
    avatarLetter: 'S',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Seleção do Quora',
    content: 'O que as pessoas que fingem ser ricas andam fazendo',
    subContent: 'Resposta: Namorei uma moça que na maioria das vezes',
    time: '10:15',
  },
  {
    id: 2,
    avatarLetter: 'J',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Jordi Henrique Marques',
    content: 'Jordi Henrique acabou de enviar uma m...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 3,
    avatarLetter: 'T',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Thiago Henrique Marques',
    content: 'Jordi Henrique acabou de enviar uma m...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 4,
    avatarLetter: 'I',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Investing.com',
    content: 'Jordi Henrique acabou de enviar uma m...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 5,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 6,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 7,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 8,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 9,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 10,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 11,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 12,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 13,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 14,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 15,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 16,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 17,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 18,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 19,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 20,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
]
