export const mailData = [
  {
    id: 1,
    avatarLetter: 'W',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Welcome to my project!',
    content: 'Do you like it?',
    subContent: 'its UI clone, but without all funcionalities',
    time: '7 am',
  },
  {
    id: 2,
    avatarLetter: 'H',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Hire me as dev for your project',
    content: 'Contact me and lets talk',
    subContent: 'I am sure that we can make it!',
    time: '8 am',
  },
  {
    id: 3,
    avatarLetter: 'T',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'This project is just portfolio',
    content: 'I decided to bring me to next level',
    subContent: 'and chanllenged myself to make this UI',
    time: '9 am',
  },
  {
    id: 4,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Do you have app ideas?',
    content: 'Cool, lets take it out of paper',
    subContent: 'and make it happen ASAP!',
    time: '10 am',
  },
  {
    id: 5,
    avatarLetter: 'W',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Wanna see my entire portfolio?',
    content: 'thiagomunich.github.io',
    subContent: 'visit the link above!',
    time: '11 am',
  },
  {
    id: 6,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 7,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 8,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 9,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 10,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 11,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 12,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 13,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 14,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 15,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 16,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 17,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 18,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 19,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '16 pm',
  },
  {
    id: 20,
    avatarLetter: 'L',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Lorem Ipsum',
    content: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
    subContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    time: '08:46',
  },
]
