export const mailData = [
  {
    id: 1,
    avatarLetter: 'W',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Welcome to my project!',
    content: 'I decided to clone Gmail UI for fun',
    subContent: 'and this is it, but without all funcionalities',
    time: '10:15',
  },
  {
    id: 2,
    avatarLetter: 'H',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Hire me as dev for your project',
    content: 'Contact me and lets talk about your ideas',
    subContent: 'I am sure that we can make it!',
    time: '08:46',
  },
  {
    id: 3,
    avatarLetter: 'T',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'This project iS just for learning purposes',
    content: 'I decided to bring me to next level',
    subContent: 'and chanllenged myself to make this UI',
    time: '08:46',
  },
  {
    id: 4,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Do you have app ideas?',
    content: 'Cool, lets take it out of the paper',
    subContent: 'and make it happen ASAP!',
    time: '08:46',
  },
  {
    id: 5,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 6,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 7,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 8,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 9,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 10,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 11,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 12,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 13,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 14,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 15,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 16,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 17,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 18,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 19,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
  {
    id: 20,
    avatarLetter: 'D',
    avatarColor: '#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6),
    title: 'Digital Ocean',
    content: 'Sua fatura está disponível em uma men...',
    subContent: 'LinkedIn você tem 1 mensagem nova pa..',
    time: '08:46',
  },
]
